### ISSUE TITLE
How to add the image.load function

### ISSUE THREAD

**Issue by tzupingkao** [soumith/torch-android#27]
Hello 

I want to use the image.load (torch/image) funciton to load PNG file in the android-demo-cifar project.

But I find that the image.load does not work, because there is not libpng.so provided by the png.c in distro/pkg/image directory.

I try to modify the CMakeList.txt (in distro/pkg/image directory) in line 56 to line 66 to build a libpng.so.

The modified part:

SET(src png.c)
SET(PNG_INCLUDE_DIR /home/tzuping/wistron_develop/torch_t7/porting/libpng/install/include)  #for png.h
SET(PNG_LIBRARIES libpng.a)
LINK_DIRECTORIES(/home/tzuping/wistron_develop/torch_t7/porting/libpng/install/lib)  #for libz.so in the ndk 
LINK_DIRECTORIES(/home/tzuping/install/android_studio/ndk/ndk-standalone-tool/sysroot/usr/lib) #for libpng.a by the libpng-1.6.21
include_directories (${PNG_INCLUDE_DIR})
ADD_TORCH_PACKAGE(png "${src}" "${luasrc}" "Image Processing")
TARGET_LINK_LIBRARIES(png luaT TH ${PNG_LIBRARIES} z)

----The original part----
# if (PNG_FOUND)
# SET(src png.c)
# include_directories (${PNG_INCLUDE_DIR})
# ADD_TORCH_PACKAGE(png "${src}" "${luasrc}" "Image Processing")
# TARGET_LINK_LIBRARIES(png luaT TH ${PNG_LIBRARIES})
# IF(LUALIB)
# TARGET_LINK_LIBRARIES(png ${LUALIB})
# ENDIF()
# else (PNG_FOUND)
# message ("WARNING: Could not find PNG libraries, PNG wrapper will not be installed")
# endif (PNG_FOUND)

But I run the android-demo-cifar app, the system logcat gives me the following error message:

06-07 23:31:10.344  4032  4032 I Torch-cifar-demo: xlua packagelibpng
06-07 23:31:10.344  4032  4032 I Torch-cifar-demo: error loading module 'libpng' from file '/data/app-lib/com.torchandroid.cifardemo-2/libpng.so':
06-07 23:31:10.344  4032  4032 I Torch-cifar-demo:  undefined symbol: luaopen_libpng
06-07 23:31:10.344  4032  4032 I Torch-cifar-demo: warning: <libpng> could not be loaded (is it installed?)

Ihave confirmed the luaopen_libpng function in the libpng.so (through the "nm -D libpng.so" command).

So Could you suggest me how to modify your project to compile the libpng.so file.

**Comment by borisfom** [comment]
The reason PNG_FOUND is false is because for some reason build script did not built/installed external/libpng. Are you using ./build.sh to build ?
This is part of the log that installs external/libpng before building/configuring anything:

Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: ""
-- Up-to-date: /home/bfomitchev/git/torch-android/install/lib/libpng16.so.16.20.0
-- Up-to-date: /home/bfomitchev/git/torch-android/install/lib/libpng16.so.16
-- Up-to-date: /home/bfomitchev/git/torch-android/install/lib/libpng16.so
-- Up-to-date: /home/bfomitchev/git/torch-android/install/lib/libpng16.a
-- Up-to-date: /home/bfomitchev/git/torch-android/install/lib/libpng.so
-- Up-to-date: /home/bfomitchev/git/torch-android/install/lib/libpng.a
-- Up-to-date: /home/bfomitchev/git/torch-android/install/include/png.h
-- Up-to-date: /home/bfomitchev/git/torch-android/install/include/pngconf.h
-- Up-to-date: /home/bfomitchev/git/torch-android/install/include/pnglibconf.h
-- Up-to-date: /home/bfomitchev/git/torch-android/install/include/libpng16/png.h
-- Up-to-date: /home/bfomitchev/git/torch-android/install/include/libpng16/pngconf.h
-- Up-to-date: /home/bfomitchev/git/torch-android/install/include/libpng16/pnglibconf.h
-- Up-to-date: /home/bfomitchev/git/torch-android/install/bin/libpng-config
-- Up-to-date: /home/bfomitchev/git/torch-android/install/bin/libpng16-config
-- Up-to-date: /home/bfomitchev/git/torch-android/install/share/man/man3/libpng.3
-- Up-to-date: /home/bfomitchev/git/torch-android/install/share/man/man3/libpngpf.3
-- Up-to-date: /home/bfomitchev/git/torch-android/install/share/man/man5/png.5
-- Up-to-date: /home/bfomitchev/git/torch-android/install/lib/pkgconfig/libpng.pc
-- Up-to-date: /home/bfomitchev/git/torch-android/install/bin/libpng-config
-- Up-to-date: /home/bfomitchev/git/torch-android/install/lib/pkgconfig/libpng16.pc
-- Up-to-date: /home/bfomitchev/git/torch-android/install/bin/libpng16-config
-- Up-to-date: /home/bfomitchev/git/torch-android/install/lib/libpng/libpng16.cmake
-- Installing: /home/bfomitchev/git/torch-android/install/lib/libpng/libpng16-noconfig.cmake
externals installed
==== Building LuaJIT 2.1.0-beta1 ====

**Comment by czhang96** [comment]
Help please, I also have the same issue, but I am using `build.sh` to build, and the output makes it seem like `libpng` is being built correctly. More detail in my issue : https://github.com/soumith/torch-android/issues/64
